//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearAction_Chat.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClearActionChat_Conversion
    {
        public ClearActionChat_Conversion()
        {
            this.ClearActionChat_Conversion_FromSent = new HashSet<ClearActionChat_Conversion_FromSent>();
        }
    
        public long Id { get; set; }
        public string SentByUserId { get; set; }
        public string ConversionText { get; set; }
        public string SentDateTime { get; set; }
        public Nullable<bool> IsAttachment { get; set; }
        public string Attachment_OriginalName { get; set; }
        public string Attachment_StoreName { get; set; }
    
        public virtual ICollection<ClearActionChat_Conversion_FromSent> ClearActionChat_Conversion_FromSent { get; set; }
    }
}
