//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ClearActionLocalDBEntities : DbContext
{
    public ClearActionLocalDBEntities()
        : base("name=ClearActionLocalDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<ClearActionChat_Conversion> ClearActionChat_Conversion { get; set; }
    public DbSet<ClearActionChat_Conversion_FromSent> ClearActionChat_Conversion_FromSent { get; set; }
}
