'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls
    
    Partial Public Class TopHeader
        
        '''<summary>
        '''lblTopicCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTopicCount As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''hyperlinkNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hyperlinkNew As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''btnMyVault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMyVault As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''btnShowAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnShowAll As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''pnlBlogSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlBlogSearch As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''txtSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lnkSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkSearch As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''btnAllCat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAllCat As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''dataListGlobalCat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dataListGlobalCat As Global.System.Web.UI.WebControls.DataList
    End Class
End Namespace
