'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Blog
    
    '''<summary>
    '''btnAddBlog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddBlog As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''litTrackback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrackback As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlTopHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTopHeader As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''topheader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topheader As Global.DotNetNuke.Modules.Blog.Controls.TopHeader
    
    '''<summary>
    '''pnlListings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlListings As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''divfilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divfilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnAllBlog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAllBlog As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btntodo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btntodo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDoneBlog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDoneBlog As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ddSortBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddSortBy As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''NavFirstBtn1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NavFirstBtn1 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''NavImagePrev1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NavImagePrev1 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblPaingTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaingTop As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''NavImageNext1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NavImageNext1 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''NavImageLast1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NavImageLast1 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ltrlCtrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrlCtrl As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearch As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ltrAuthorlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrAuthorlist As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltrPreviousPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrPreviousPost As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''hdnCurrentPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCurrentPage As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnTotalRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTotalRecord As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''pnlDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDetails As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ltrlCtrlDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrlCtrlDetail As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltrlBlogHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrlBlogHeader As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''txtComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComments As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''UploadedAttachmentSavePost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UploadedAttachmentSavePost As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxAttachmentData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxAttachmentData As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rptComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptComments As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''lblMemberCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMemberCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptActiveMember control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptActiveMember As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''lblNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ltrlFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrlFiles As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''rptSharedFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSharedFiles As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''Paging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Paging As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''NavFirstBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NavFirstBtn As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''NavImagePrev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NavImagePrev As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblPagerInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPagerInfo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''NavImageNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NavImageNext As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''NavImageLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NavImageLast As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''hdnFileUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFileUrl As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFileName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnCommentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCommentID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnContentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnContentID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnFileUrlReplies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFileUrlReplies As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnFileNameReplies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFileNameReplies As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnCommentIDReplies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCommentIDReplies As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnContentIDReplies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnContentIDReplies As Global.System.Web.UI.WebControls.HiddenField
End Class
